# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe8d3bd9e1d7bf0a2e52534040b84dec8f8a7f72be13e9e380f6a45d9a62b0e113de0b67d8c9947648f0324154681048d1badbe0fe3ead2d4aa6149b7d29e2a6

test:
  secret_key_base: dce9030d70ff6952833f0488d568e610fad7218fa24cea6351e13590aecb0d90c42770e75811e774544ad10436c6d49b993b465cfcfe279699e499fb61f25ddd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
